"use client";
import { useState } from "react";

const architectures = {
  Web2: [["User", "You sign in to an account controlled by the platform."], ["Frontend", "The interface sends requests to the platform’s API."], ["Backend", "The operator runs business logic and authorizes database writes."], ["Database", "The platform maintains the authoritative record of balances, items, and permissions."]],
  Web3: [["User", "You choose an application and an action."], ["Wallet", "You review and sign a request. Connecting alone does not authorize every transaction."], ["Frontend", "The interface prepares contract calls and submits signed requests through an RPC provider."], ["Smart Contract", "Validating nodes execute the same rules to check a proposed state change."], ["Blockchain", "The network agrees on shared state, such as which address owns a token."]],
};
export function ArchitectureExplorer() {
  const [mode, setMode] = useState<"Web2" | "Web3" | "Compare">("Compare");
  const [selected, setSelected] = useState({ Web2: 3, Web3: 4 });
  return <div className="lesson-demo"><div className="lesson-toggle" role="group" aria-label="Architecture view">{(["Web2", "Web3", "Compare"] as const).map(m => <button key={m} aria-pressed={m === mode} onClick={() => setMode(m)}>{m}</button>)}</div><p className="demo-hint">Select a step to inspect its responsibility.</p>{(["Web2", "Web3"] as const).filter(m => mode === "Compare" || mode === m).map(m => <div className="architecture" key={m}><h3>{m} <small>{m === "Web2" ? "Platform-controlled state" : "Shared, verifiable state"}</small></h3><div className="architecture-flow">{architectures[m].map(([name], i) => <button key={name} aria-pressed={selected[m] === i} onClick={() => setSelected({ ...selected, [m]: i })}>{name}{i < architectures[m].length - 1 && <span aria-hidden="true"> →</span>}</button>)}</div><p className="lesson-feedback" aria-live="polite"><strong>{architectures[m][selected[m]][0]}.</strong> {architectures[m][selected[m]][1]}</p></div>)}<p className="demo-hint">A simplified write flow, not a mandatory network topology. Wallet and frontend communicate; public reads usually need no signature. Real DApps often also use backends, databases, RPC providers, and indexers.</p></div>;
}
const decisions = [
  { title: "Your Onward3 profile and quiz score", answer: "Off-chain", why: "Store application data in PostgreSQL. The app needs fast updates and private, deletable records; network consensus adds little here.", factors: ["Cost: low-cost writes", "Performance: fast updates", "Privacy: access control and deletion", "Trust: app-managed learning records are sufficient"] },
  { title: "Which address owns NFT #9527?", answer: "On-chain", why: "Ownership is shared state that independent applications may need to verify without relying on the game company’s database. Contract permissions still matter.", factors: ["Cost: pay for state changes", "Performance: wait for confirmation", "Privacy: addresses and activity are public", "Trust: independently verifiable ownership"] },
  { title: "A keyboard review: “Five stars!”", answer: "Off-chain", why: "An ordinary product review rarely needs blockchain consensus. Moderation, search, editing, and deletion are easier in a database.", factors: ["Cost: avoid replicated storage", "Performance: efficient search", "Privacy: support removal", "Trust: the platform moderates reviews"] },
  { title: "A certificate others must verify after Onward3 closes", answer: "Hybrid", why: "Keep personal information and detailed learning records offchain. An onchain credential or proof can let third parties check issuance and revocation. A signed offchain credential may also suffice; choose based on the trust requirement. The chain proves issuance, not that the learner truly mastered the material.", factors: ["Cost: minimize onchain data", "Performance: verify proofs separately", "Privacy: keep identity offchain; hashes can still leak information", "Trust: shared issuance and revocation, with trust in the issuer"] },
];
export function StorageDecisions() {
  const [answers, setAnswers] = useState<Record<number, string>>({});
  return <div className="storage-decisions">{decisions.map((d, i) => <div className="lesson-demo" key={d.title}><p className="eyebrow">DECISION 0{i + 1}</p><h3>{d.title}</h3><div className="lesson-toggle" role="group" aria-label={d.title}>{["Off-chain", "On-chain", "Hybrid"].map(a => <button key={a} aria-pressed={answers[i] === a} onClick={() => setAnswers({ ...answers, [i]: a })}>{a}</button>)}</div><div aria-live="polite">{answers[i] && <div className="lesson-feedback"><strong>{answers[i] === d.answer ? "Good fit." : `Consider ${d.answer.toLowerCase()} here.`}</strong><p>{d.why}</p><ul>{d.factors.map(f => <li key={f}>{f}</li>)}</ul></div>}</div></div>)}</div>;
}
export function OwnershipExperiment() {
  const [closed, setClosed] = useState(false);
  return <div className="lesson-demo"><div className="lesson-toggle" role="group" aria-label="Game company status"><button aria-pressed={!closed} onClick={() => setClosed(false)}>Game operating</button><button aria-pressed={closed} onClick={() => setClosed(true)}>Company shuts down</button></div><div className="ownership-grid" aria-live="polite"><article><p className="eyebrow">WEB2 GAME SKIN</p><h3>Platform inventory</h3><p><strong>Record:</strong> {closed ? "The company’s database may survive, but the service no longer honors your inventory." : "The company database records your right to use skin #9527."}</p><p><strong>Utility:</strong> {closed ? "The game is gone. The skin cannot be used there." : "Equip the skin in this game."}</p><p><strong>Value:</strong> {closed ? "No continuing market or resale right is guaranteed." : "Depends on platform rules and player demand."}</p></article><article><p className="eyebrow">NFT GAME ITEM</p><h3>Onchain ownership</h3><p><strong>Record:</strong> {closed ? "Your address can still own NFT #9527 if the network and contract state persist." : "The NFT contract records your address as owner of #9527."}</p><p><strong>Utility:</strong> {closed ? "The original game is gone. Another game must explicitly support the item." : "The game recognizes the NFT and grants its in-game use."}</p><p><strong>Value:</strong> {closed ? "May approach zero without demand. Ownership does not guarantee a buyer." : "Depends on demand, scarcity, and supported uses."}</p></article></div><p className="lesson-feedback">{closed ? "The ownership record can outlive its original platform. The experience and market value may not." : "Now shut down the company. Which guarantees actually survive?"}</p></div>;
}
