const path = [
  ["01", "Web3 basics", "Ownership, networks & the new mental model"],
  ["02", "Blockchain", "Shared state without a central database"],
  ["03", "Ethereum", "The programmable layer of the internet"],
  ["04", "Wallets", "Keys, accounts & signing—not a bank account"],
  ["05", "Smart contracts", "Backend logic that runs onchain"],
  ["06", "Build onchain", "Ship your first application"],
];
const features = [
  { number: "01", title: "Web2 mental models", text: "Learn unfamiliar ideas through the systems you already know: databases, APIs, identity, and servers.", icon: "↗" },
  { number: "02", title: "Interactive by default", text: "Change an input. Trace a transaction. See the protocol respond. Understanding sticks when you can touch it.", icon: "⌘" },
  { number: "03", title: "Built to ship", text: "Move from first principles to practical projects—with the context to make good engineering decisions.", icon: "◈" },
];
function Arrow() { return <span aria-hidden="true" className="arrow">↗</span>; }
export default function Home() {
  return <main>
    <nav className="nav shell" aria-label="Primary navigation"><a href="#top" className="wordmark" aria-label="Onward3 home">ONWARD<span>3</span></a><div className="nav-links"><a href="#path">Roadmap</a><a href="#learn">Learn</a><a href="#playground">Playground</a><a href="#about">About</a></div><a className="github-link" href="https://github.com/georgetao730/onward3" target="_blank" rel="noreferrer">GitHub <Arrow /></a></nav>
    <section className="hero shell" id="top"><div className="eyebrow"><i /> A clearer path into Web3</div><h1>From Web2 Developer<br />to <em>Web3 Builder.</em></h1><p className="hero-copy">Learn Web3 from first principles through visual explanations, interactive playgrounds, and real projects.</p><div className="hero-actions"><a className="button button-dark" href="#path">Start learning <Arrow /></a><a className="text-link" href="#playground">Explore the playground <span>↓</span></a></div><div className="hero-grid" aria-hidden="true"><span>0x</span><span>01</span><span>10</span><span>11</span><span>0x</span><span>01</span><span>10</span><span>11</span></div><div className="hero-note"><span className="pulse" /> Built for curious engineers, not crypto tourists.</div></section>
    <section className="path-section" id="path"><div className="shell"><div className="section-heading"><p className="kicker">01 / THE ROADMAP</p><div><h2>Your path<br />onchain.</h2><p>One coherent route from core concepts to your first working onchain app.</p></div></div><div className="path-list">{path.map(([number, title, description], index) => <a className="path-row" href="#learn" key={number}><span className="path-number">{number}</span><h3>{title}</h3><span className="path-description">{description}</span><span className="path-arrow">{index === 0 ? "Start here" : "Explore"} <Arrow /></span></a>)}</div><a className="button button-outline" href="#learn">View full roadmap <Arrow /></a></div></section>
    <section className="features shell" id="learn"><div className="section-heading"><p className="kicker">02 / BUILT FOR DEVELOPERS</p><div><h2>Start where<br />you already are.</h2><p>No hype. No assumed context. Just the conceptual bridges that make the unfamiliar click.</p></div></div><div className="feature-grid">{features.map((feature) => <article className="feature-card" key={feature.number}><div className="feature-top"><span>{feature.number}</span><b>{feature.icon}</b></div><h3>{feature.title}</h3><p>{feature.text}</p><a href="#path">How it works <Arrow /></a></article>)}</div></section>
    <section className="playground" id="playground"><div className="shell playground-inner"><div className="playground-copy"><p className="kicker">03 / LEARN BY DOING</p><h2>Not another<br /><em>video course.</em></h2><p>Play with the building blocks. Learn what a wallet actually does before you connect one to your app.</p><a className="button button-light" href="#playground">Open Wallet Playground <Arrow /></a></div><div className="terminal" aria-label="Wallet playground preview"><div className="terminal-bar"><span /><span /><span /><b>wallet.playground</b><em>● live</em></div><div className="terminal-content"><p className="terminal-label">YOUR ACCOUNT</p><div className="key-row"><span>Private key</span><code>••••••••••••••••</code><button aria-label="Reveal private key">⌁</button></div><div className="terminal-line" /><p className="terminal-label">DERIVED ADDRESS</p><code className="address">0x7f2A...9C1e</code><div className="transaction"><span>sign transaction</span><b>↳</b><code>verified</code></div><div className="terminal-caption">Your keys stay in your browser. Always.</div></div></div></div></section>
    <section className="final-cta shell" id="about"><p className="kicker">THE FIRST BLOCK</p><h2>Ready to build<br />what&apos;s <em>next?</em></h2><p>The next generation of the internet needs thoughtful builders. Start with the foundations.</p><a className="button button-dark" href="#path">Begin your journey <Arrow /></a></section>
    <footer className="footer shell"><a href="#top" className="wordmark">ONWARD<span>3</span></a><p>Web3, explained for builders.</p><div><a href="https://github.com/georgetao730/onward3" target="_blank" rel="noreferrer">GitHub</a><a href="#top">Back to top ↑</a></div></footer>
  </main>;
}
