import { Analogy, CodeBlock } from "@/components/lesson/lesson-blocks";
import { ArchitectureExplorer, OwnershipExperiment, StorageDecisions } from "@/components/lesson/web3-interactions";
import type { LessonContent } from "./types";

export const whatIsWeb3: LessonContent = {
  slug: "what-is-web3", number: "01", duration: "18 min",
  title: "What Really Changes from Web2 to Web3?",
  subtitle: "You already know how Web2 works. Let’s start from there.",
  objective: "By the end, you will be able to decide what belongs onchain—and explain what ownership does and does not guarantee.",
  next: { slug: "blockchain", title: "Blockchain", available: false },
  sections: [
    { id: "big-shift", title: "The Big Shift", content: <><p>You buy a game skin. Somewhere, a backend writes a row saying your account can use it. The platform controls that record and the rules around it. If the game closes, your purchase no longer gives you a working game item.</p><p>Now imagine the ownership record lives in a shared network. Independent applications can verify which address owns the item without asking the game company. This is a useful starting point for Web3: <strong>platform-controlled state → shared, verifiable state.</strong></p><Analogy>Your database answers “what does our application say?” A blockchain can answer “what state has this network agreed on?” This matters when participants need a common record without giving one platform sole control.</Analogy><p>This does not remove every trusted party. Contract administrators, interfaces, network assumptions, and external data can still affect the system. Ask who can change the rules.</p></> },
    { id: "architecture", title: "Web2 vs Web3 Architecture", content: <><p>You still build interfaces. What changes is how some actions are authorized, executed, and recorded. Follow one write through each system.</p><ArchitectureExplorer /></> },
    { id: "mental-model", title: "Your Web2 Mental Model", content: <><p>Keep your engineering instincts. Change the assumptions at the boundary.</p><div className="lesson-table-wrap" tabIndex={0} role="region" aria-label="Web2 and Web3 mental model comparison"><table className="lesson-table"><thead><tr><th scope="col">Concern</th><th scope="col">Familiar Web2 model</th><th scope="col">Web3 possibility</th></tr></thead><tbody>{[
      ["Identity", "Platform account + session", "An address + signatures proving control; not proof of a real-world identity."],
      ["Data", "Application database", "Shared onchain state plus offchain application data."],
      ["Logic", "Backend business logic", "Smart contracts for shared rules; backends still handle other work."],
      ["Assets", "Platform-managed inventory", "Tokens recorded against an address under contract rules."],
      ["Trust", "Trust the operator to maintain the record", "Verify network state and contract rules; assess remaining admin and infrastructure trust."],
    ].map(row => <tr key={row[0]}><th scope="row">{row[0]}</th><td>{row[1]}</td><td>{row[2]}</td></tr>)}</tbody></table></div></> },
    { id: "wallet", title: "Wallet: Control, Verify, Identify", content: <><p>For a basic key-controlled account, a wallet helps manage keys and request signatures. Assets are recorded on the chain; they are not files stored inside the wallet app.</p><div className="concept-cards"><article><h3>Private Key → Control</h3><p>Authorizes signatures. Keep it secret; anyone who obtains it can act as that key-controlled account.</p></article><article><h3>Public Key → Verify</h3><p>Used to verify signatures. It is derived from the private key, without exposing the secret.</p></article><article><h3>Address → Identify</h3><p>A public account identifier. For an Ethereum key-controlled account, it is derived from the public key.</p></article></div><Analogy>A wallet is an identity-and-signing client. Wallet ≠ Alipay: a self-custody wallet does not rely on a payment company’s private balance ledger. Wallet ≠ DApp frontend: the app proposes actions; your wallet lets you review and authorize them.</Analogy><p>A public address is enough to look up public holdings. Connecting a wallet does not itself transfer assets. Signing can authorize meaningful actions, so the requested operation matters. Smart-contract wallets can use more complex authorization rules.</p></> },
    { id: "smart-contract", title: "Business Logic, Different Constraints", content: <><p><strong>Smart Contract ≈ backend business logic.</strong> It checks rules and changes state. But an Ethereum contract is not a Spring Boot service running on your server.</p><ul><li><strong>Deterministic:</strong> given the same starting state and execution inputs, validating nodes must obtain the same result.</li><li><strong>Public:</strong> deployed code and onchain state are inspectable. A “private” storage variable is not a secret vault.</li><li><strong>Gas:</strong> onchain execution is metered. State-changing transactions cost gas; local read calls usually do not charge the reader an onchain fee.</li><li><strong>No arbitrary internet access:</strong> a contract cannot directly fetch an HTTP API. External facts need to be submitted, often through an oracle, which introduces trust assumptions.</li></ul><CodeBlock label="Mental model · illustrative pseudocode, not deployable code" code={'// Web2: platform authorizes a database write\nbackend.purchaseSkin(userId, skinId)\ndb.inventory.insert({ userId, skinId })\n\n// Web3: user signs; network validates contract rules\ntransaction = wallet.sign(contractCall)\nnetwork.execute(transaction)\nNFT.ownerOf(9527) // → owner address'} /><p>Deployed code may be fixed, but upgrade mechanisms and admin permissions can change behavior. Read the actual rules before assuming a contract removes operator control.</p></> },
    { id: "storage", title: "What Belongs Onchain?", content: <><p><strong>Databases store data the application needs. Blockchains store state that multiple participants need to verify together and that should not be changed at one platform’s discretion.</strong></p><p>“Important” is not the same as “belongs onchain.” Compare cost, performance, privacy, and the trust requirement. Personal information generally belongs offchain with appropriate protection.</p><StorageDecisions /><Analogy>A practical DApp often combines PostgreSQL, a backend, search, and an indexer with smart contracts. Put shared ownership or settlement onchain when the guarantees justify the tradeoffs.</Analogy></> },
    { id: "ownership", title: "Ownership ≠ Utility ≠ Value", content: <><p>You paid for the skin. But what survives when the company stops maintaining the game? Change the scenario below.</p><OwnershipExperiment /><p><strong>Ownership:</strong> which address the contract records as owner. <strong>Utility:</strong> what applications let you do with the token. <strong>Value:</strong> what someone is willing to exchange for it. These are separate questions.</p><p>Any application capable of reading the relevant chain and contract can verify the ownership record. It does not follow that every DApp will display the NFT or every game will support it. Token ownership also does not automatically grant copyright or commercial rights.</p><CodeBlock label="The image may live somewhere else" code={'NFT contract → token ID → tokenURI\n                          ↓\n                      metadata → image\n\n// If company.com disappears, this can break:\nhttps://company.com/nft/9527.json'} /><p>The token can survive while its artwork disappears. Onchain metadata, IPFS, and Arweave have different storage and persistence assumptions; a link alone is no guarantee that someone will keep hosting the content.</p></> },
    { id: "takeaways", title: "Key Takeaways", content: <ul className="takeaway-list"><li>The central shift is who controls and verifies shared state.</li><li>A wallet signs; an address identifies; the chain records holdings.</li><li>Contracts resemble business logic with a different execution and trust model.</li><li>Keep application data offchain unless shared verification justifies the tradeoffs.</li><li>Ownership can persist without a useful game, accessible artwork, or market demand.</li></ul> },
  ],
  quiz: [
    { id: "quiz-storage", prompt: "Where should Onward3 store a nickname and quiz score?", options: ["Onchain, because all important data belongs there", "In its application database", "Inside the user’s wallet"], answer: 1, explanation: "These are application records. Fast updates, privacy, and deletion matter more than shared consensus." },
    { id: "quiz-wallet", prompt: "What does a basic self-custody wallet primarily help you do?", options: ["Store NFT images and run every DApp", "Maintain a payment company’s private balance", "Manage keys and authorize actions with signatures"], answer: 2, explanation: "The wallet is a signing client. The network records holdings; the DApp supplies the application interface." },
    { id: "quiz-nft", prompt: "The game company closes. What can still hold true for its NFT?", options: ["Ownership remains verifiable if the chain and contract state persist", "Every other game must accept it", "Its image and resale value are guaranteed forever"], answer: 0, explanation: "A surviving ownership record does not guarantee utility, available metadata, or market value." },
  ],
};
